services:
  - type: web
    name: cashure-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cashure-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET_NAME
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
    healthCheckPath: /api/health

databases:
  - name: cashure-db
    databaseName: cashure
    user: cashure_user